version: "3.3"

services:
  datadog:
    image: public.ecr.aws/datadog/agent:7
    container_name: datadog_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      DD_API_KEY: $DD_API_KEY
      DD_SITE: $DD_SITE
      DD_LOGS_ENABLED: 'true'
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: 'true'
      DD_PROCESS_AGENT_ENABLED: 'true'
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: 'true'
      DD_REMOTE_CONFIGURATION_ENABLED: 'true'
      DD_REMOTE_CONFIGURATION_KEY: $DD_REMOTE_CONFIGURATION_KEY
    restart: unless-stopped
    ports:
      - "8125:8125/udp"
      - "8126:8126/tcp"
    labels:
      # Datadog
      com.datadoghq.tags.env: prod
      com.datadoghq.tags.service: agent
      com.datadoghq.tags.version: 7
      com.datadoghq.ad.logs: '[{"source": "agent", "service": "datadog"}]'

      
  my_shop:
    build: .
    container_name: my_shop
    ports:
      - 8080:3000
    environment:
      DD_AGENT_HOST: datadog
      DD_ENV: prod
      DD_LOGS_INJECTION: 'true'
      DD_PROFILING_ENABLED: 'true'
      DD_APPSEC_ENABLED: 'true'
      DD_REMOTE_CONFIG_ENABLED: 'true'
      DD_VERSION: $REV
      DD_TAGS: "git.commit.sha:$REV,git.repository_url:github.com/abruneau/Datadog_for_dev"
      DD_TRACE_STARTUP_LOGS: 'true'   