name: validations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    env:
      REF_TO_TEST: ${{ github.event.inputs.branch || 'main' }}
      DD_SERVICE: my_shop
      DD_CIVISIBILITY_AGENTLESS_ENABLED: 1
      DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DD_APPLICATION_KEY: ${{ secrets.DD_APPLICATION_KEY }}
      DD_CIVISIBILITY_GIT_UPLOAD_ENABLED: true
      DD_CIVISIBILITY_ITR_ENABLED: true
      DD_ENV: ci
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test:ci
